### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by Zhangpeigeng** [huangzizheng01/ShuffleMamba#1]
Hi, thanks for your amazing work! I'm using my desktop with two GPUs RTX 3090 and 4090 to train my model. However, I encountered the CUDA out of memory. Could you give me some suggestions? Thanks!

**Comment by huangzizheng01** [comment]
Hi! Thanks for your interest. To run the training script, you may adopt a smaller batch size, like 32, on each GPU. The line can be adjusted as `--batch 32`, and the base learning rate may also be adjusted to a reasonable value.

**Comment by Zhangpeigeng** [comment]
Thanks for your replying! I tried to use a smaller batch size and it works!
